# Generated by Django 4.0.4 on 2022-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM_VISITA', 'Em Visita'), ('FINALIZADO', 'Visita Fianlizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.PositiveSmallIntegerField(verbose_name='Número da casa'),
        ),
    ]
