# Generated by Django 4.0.4 on 2022-04-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_visitante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
